import = [
    "~/.config/alacritty/themes/themes/nord_light.toml"
]

#"~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"

[bell]
duration = 500

[cursor.style]
blinking = "On"

[font]
size = 14.0

[font.bold]
family = "MesloLGS NF"

[font.bold_italic]
family = "MesloLGS NF"

[font.italic]
family = "MesloLGS NF"

[font.normal]
family = "MesloLGS NF"

[window.padding]
x = 10
y = 10
